-----------------------------------------------------------------------------
Run case  1:  Conventional Tail Trim at Alpha = 3.5 deg

alpha        ->  alpha       =   3.50000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
